import { createClient } from '@supabase/supabase-js'
import { OpenAIEmbeddings } from '@langchain/openai'
import { RecursiveCharacterTextSplitter } from 'langchain/text_splitter'
import { SupabaseVectorStore } from 'langchain/vectorstores/supabase'
import { NextResponse } from 'next/server'

export async function GET() {
  try {
    const splitter = new RecursiveCharacterTextSplitter({
      chunkSize: 500,
      chunkOverlap: 50,
      separators: ['\n\n', '\n', ' ', ''] // default setting
    })

    const output = await splitter.createDocuments(data)

    const sbApiKey = process.env.SUPABASE_SERVICE_ROLE_KEY
    const sbUrl = process.env.SUPABASE_URL
    const openAIApiKey = process.env.OPENAI_API_KEY

    const client = createClient(sbUrl as string, sbApiKey as string)

    await SupabaseVectorStore.fromDocuments(
      output,
      new OpenAIEmbeddings({ openAIApiKey }),
      {
        client,
        tableName: 'documents'
      }
    )
    return new NextResponse()
  } catch (err) {
    console.log(err)
    return new NextResponse()
  }
}

const data = [
  'Tutor name: Dr. Alice Brown\nTutor strengths: Problem-solving, Critical thinking, Clear communication\nTutor expertise: Computer Science, Algorithms, Data Structures\nBio: Dr. Alice Brown is a computer science expert passionate about empowering students. Her areas of strength lie in algorithm design, data structures, and fostering critical thinking and problem-solving skills. Dr. Brown excels at explaining complex concepts with clear communication, making her an ideal mentor for students seeking guidance in these areas.',
  "Tutor name: Professor David Chen\nTutor strengths: Patience, Motivation, Enthusiasm\nTutor expertise: Mathematics, Calculus, Linear Algebra\nBio: Professor David Chen is a mathematics professor known for his patience and enthusiasm in teaching. With expertise in calculus and linear algebra, he is dedicated to motivating students to excel in their mathematical studies. Professor Chen's passion for mathematics and commitment to student success make him an excellent mentor for those seeking guidance in these subjects.",
  "Tutor name: Ms. Emily Garcia\nTutor strengths: Creativity, Feedback, Encouragement\nTutor expertise: English Literature, Creative Writing, Public Speaking\nBio: Ms. Emily Garcia is an English literature expert with a passion for creative writing and public speaking. Her strengths lie in fostering creativity, providing constructive feedback, and offering encouragement to aspiring writers and speakers. Ms. Garcia's dedication to helping students develop their writing and speaking skills makes her an ideal mentor for those seeking guidance in these areas.",
  "Tutor name: Mr. Frederick Evans\nTutor strengths: Storytelling, Research skills, Organization\nTutor expertise: History, World History, European History\nBio: Mr. Frederick Evans is a history enthusiast with expertise in world history and European history. Known for his storytelling abilities, research skills, and organizational talents, he is dedicated to helping students explore the past and develop a deeper understanding of historical events. Mr. Evans' passion for history and commitment to student success make him an excellent mentor for those seeking guidance in these subjects.",
  "Tutor name: Ms. Olivia Hernandez\nTutor strengths: Enthusiasm, Clear communication, Hands-on learning\nTutor expertise: Biology, Anatomy, Physiology\nBio: Ms. Olivia Hernandez is a biology expert passionate about anatomy and physiology. With strengths in enthusiasm, clear communication, and hands-on learning, she is dedicated to helping students explore the wonders of the human body. Ms. Hernandez's passion for biology and commitment to student success make her an excellent mentor for those seeking guidance in these subjects.",
  "Tutor name: Mr. Noah Jackson\nTutor strengths: Critical thinking, Analytical skills, Problem-solving\nTutor expertise: Chemistry, Organic Chemistry, Inorganic Chemistry\nBio: Mr. Noah Jackson is a chemistry expert with a focus on organic and inorganic chemistry. Known for his critical thinking, analytical skills, and problem-solving abilities, he is dedicated to helping students master the principles of chemistry. Mr. Jackson's passion for chemistry and commitment to student success make him an excellent mentor for those seeking guidance in these subjects.",
  "Tutor name: Ms. Sophia Khan\nTutor strengths: Patience, Motivation, Mentorship\nTutor expertise: Physics, Mechanics, Electricity and Magnetism\nBio: Ms. Sophia Khan is a physics expert with a focus on mechanics and electricity and magnetism. Known for her patience, motivation, and mentorship skills, she is dedicated to helping students understand the laws of the universe. Ms. Khan's passion for physics and commitment to student success make her an excellent mentor for those seeking guidance in these subjects.",
  "Tutor name: Mr. Liam Lee\nTutor strengths: Empathy, Active listening, Communication skills\nTutor expertise: Psychology, Social Psychology, Developmental Psychology\nBio: Mr. Liam Lee is a psychology expert with a focus on social and developmental psychology. Known for his empathy, active listening, and communication skills, he is dedicated to helping students explore the complexities of the human mind. Mr. Lee's passion for psychology and commitment to student success make him an excellent mentor for those seeking guidance in these subjects.",
  "Tutor name: Ms. Ava Martinez\nTutor strengths: Critical thinking, Research skills, Writing skills\nTutor expertise: Sociology, Anthropology, Social Justice\nBio: Ms. Ava Martinez is a sociology expert with a focus on anthropology and social justice. Known for her critical thinking, research skills, and writing abilities, she is dedicated to helping students understand social structures and inequalities. Ms. Martinez's passion for sociology and commitment to student success make her an excellent mentor for those seeking guidance in these subjects.",
  "Tutor name: Mr. Ethan Miller\nTutor strengths: Analytical skills, Problem-solving, Communication skills\nTutor expertise: Economics, Macroeconomics, Microeconomics\nBio: Mr. Ethan Miller is an economics expert with a focus on macroeconomics and microeconomics. Known for his analytical skills, problem-solving abilities, and communication skills, he is dedicated to helping students understand the principles of economics. Mr. Miller's passion for economics and commitment to student success make him an excellent mentor for those seeking guidance in these subjects.",
  "Tutor name: Ms. Isabella Garcia\nTutor strengths: Critical thinking, Debate skills, Writing skills\nTutor expertise: Philosophy, Ethics, Logic\nBio: Ms. Isabella Garcia is a philosophy expert with a focus on ethics and logic. Known for her critical thinking, debate skills, and writing abilities, she is dedicated to helping students explore the fundamental questions of existence. Ms. Garcia's passion for philosophy and commitment to student success make her an excellent mentor for those seeking guidance in these subjects.",
  "Tutor name: Mr. James Moore\nTutor strengths: Research skills, Communication skills, Public speaking\nTutor expertise: Political Science, International Relations, Comparative Politics\nBio: Mr. James Moore is a political science expert with a focus on international relations and comparative politics. Known for his research skills, communication abilities, and public speaking talents, he is dedicated to helping students understand the complexities of global governance. Mr. Moore's passion for political science and commitment to student success make him an excellent mentor for those seeking guidance in these subjects.",
  "Tutor name: Ms. Charlotte Parker\nTutor strengths: Creativity, Analysis, Communication skills\nTutor expertise: Literature, Poetry, Drama\nBio: Ms. Charlotte Parker is a literature expert with a passion for poetry and drama. Known for her creativity, analysis, and communication skills, she is dedicated to helping students explore the world of literary arts. Ms. Parker's passion for literature and commitment to student success make her an excellent mentor for those seeking guidance in these subjects.",
  "Tutor name: Mr. William Davis\nTutor strengths: Enthusiasm, Cultural awareness, Patience\nTutor expertise: French, Spanish, German\nBio: Mr. William Davis is a language expert with proficiency in French, Spanish, and German. Known for his enthusiasm, cultural awareness, and patience, he is dedicated to helping students master foreign languages. Mr. Davis' passion for languages and commitment to student success make him an excellent mentor for those seeking guidance in these subjects.",
  "Tutor name: Ms. Evelyn Taylor\nTutor strengths: Creativity, Critical thinking, Visual communication\nTutor expertise: Art History, Studio Art, Art Theory\nBio: Ms. Evelyn Taylor is an art history expert with a focus on studio art and art theory. Known for her creativity, critical thinking, and visual communication skills, she is dedicated to helping students explore the world of art. Ms. Taylor's passion for art and commitment to student success make her an excellent mentor for those seeking guidance in these subjects.",
  "Tutor name: Mr. Gabriel Rodriguez\nTutor strengths: Passion, Motivation, Mentorship\nTutor expertise: Music Theory, Music Composition, Music Performance\nBio: Mr. Gabriel Rodriguez is a music expert with a focus on music theory, composition, and performance. Known for his passion, motivation, and mentorship skills, he is dedicated to helping students develop their musical talents. Mr. Rodriguez's love for music and commitment to student success make him an excellent mentor for those seeking guidance in these subjects.",
  "Tutor name: Ms. Sofia Hernandez\nTutor strengths: Creativity, Communication skills, Collaboration\nTutor expertise: Theatre, Acting, Directing\nBio: Ms. Sofia Hernandez is a theatre expert with a passion for acting and directing. Known for her creativity, communication skills, and collaborative spirit, she is dedicated to helping students explore the world of theatre arts. Ms. Hernandez's passion for theatre and commitment to student success make her an excellent mentor for those seeking guidance in these subjects.",
  "Tutor name: Mr. Michael Young\nTutor strengths: Creativity, Technical skills, Storytelling\nTutor expertise: Film Studies, Video Production, Screenwriting\nBio: Mr. Michael Young is a film studies expert with a focus on video production and screenwriting. Known for his creativity, technical skills, and storytelling abilities, he is dedicated to helping students bring their cinematic visions to life. Mr. Young's passion for film and commitment to student success make him an excellent mentor for those seeking guidance in these subjects.",
  "Tutor name: Ms. Chloe Wilson\nTutor strengths: Research skills, Writing skills, Critical thinking\nTutor expertise: Journalism, Media Studies, Communication\nBio: Ms. Chloe Wilson is a journalism expert with a focus on media studies and communication. Known for her research skills, writing abilities, and critical thinking, she is dedicated to helping students navigate the world of news and media. Ms. Wilson's passion for journalism and commitment to student success make her an excellent mentor for those seeking guidance in these subjects.",
  "Tutor name: Mr. Daniel Walker\nTutor strengths: Problem-solving, Analytical skills, Technical skills\nTutor expertise: Web Development, Programming Languages, Databases\nBio: Mr. Daniel Walker is a web development expert with proficiency in programming languages and databases. Known for his problem-solving abilities, analytical skills, and technical expertise, he is dedicated to helping students master the art of coding. Mr. Walker's passion for web development and commitment to student success make him an excellent mentor for those seeking guidance in these subjects."
]
